version: "3.8"
services: 
  deepmind_jaxstk:
    build: .
    container_name: dm-jaxstk
    tty: true
    runtime: nvidia
    command: /bin/bash
    volumes:
            - ./APP:/workspace/APP
            - ./extras/lib/acme:/usr/local/lib/python3.8/dist-packages/acme
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
